# Make the shell check its window size after a process completes
shopt -s checkwinsize

# Loading completions from the appropriate directory
for compl in `find $DIRCONFIG/sh/bash/completions -maxdepth 1 -iname "[^.]*.bash-completions" -type f`; do
  source $compl 2>/dev/null || echo "Failed to load completion $compl" >&2
done

# Ensuring the default theme is loaded
source $DIRCONFIG/sh/bash/themes/default_theme.bash_theme

# Load the customization options
for custom in `find $DIRCONFIG/sh/bash/custom -maxdepth 1 -iname "[^.]*.bash" -type f`; do
  source $custom 2>/dev/null || echo "Failed to load custom $custom" >&2
done

# https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
if ! test -z ${BASH_THEME+x}; then
  source $DIRCONFIG/sh/bash/themes/"$BASH_THEME".bash_theme 2>/dev/null || echo "Failed to load theme: $BASH_THEME" >&2
fi

PROMPT_COMMAND='make_bash_prompt'
export PROMPT_COMMAND
