# Make the shell check its window size after a process completes
shopt -s checkwinsize

# Loading completions from the appropriate directory
for compl in `find $DIRCONFIG/sh/bash/completions -type f -iname "[^.]*.bash-completions" -depth 1`; do
  builtin source $compl 2>/dev/null || builtin echo "Failed to load completion $compl" >&2
done

# Ensuring the default theme is loaded
builtin source $DIRCONFIG/sh/bash/themes/default_theme.bash_theme

# Load the customization options
for custom in `find $DIRCONFIG/sh/bash/custom -type f -iname "[^.]*.bash" -depth 1`; do
  builtin source $custom 2>/dev/null || builtin echo "Failed to load custom $custom" >&2
done

# https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
if ! builtin test -z ${BASH_THEME+x}; then
  builtin source $DIRCONFIG/sh/bash/themes/"$BASH_THEME".bash_theme 2>/dev/null || builtin echo "Failed to load theme: $BASH_THEME" >&2
fi

builtin export PROMPT_COMMAND='make_bash_prompt'
