[snapshot]
max-new-file-size = "10MB"

[user]
name = "Alexis (Poliorcetics) Bourget"
email = "ab_jujutsu@poliorcetiq.eu"

[aliases]
c = ["commit"]
cm = ["commit", "-m"]
d = ["describe"]
l = ["log"]
s = ["status"]

[git]
push-branch-prefix = "ab/push-"

[template-aliases]
# Override the default short ID to use the absolute shortest, making it easier to use `-r <id>`
# in various `jj` commands
'format_short_id(id)' = 'id.shortest()'

[ui]
default-command = "status"

diff.tool = ["difft", "--color=always", "$left", "$right"]

diff-editor = "scm-diff-editor"
merge-editor = "scm-diff-editor"

[merge-tools.scm-diff-editor]
edit-args = ["--dir-diff", "$left", "$right"]
merge-args = [
    "--dir-diff",
    "--output", "$output",
    "--base", "$base",
    "$left", "$right",
]
