[snapshot]
max-new-file-size = "10MB"

[user]
name = "Alexis (Poliorcetics) Bourget"
email = "ab_jujutsu@poliorcetiq.eu"

[aliases]
b = ["branch"]
c = ["commit"]
cm = ["commit", "-m"]
d = ["diff"]
ds = ["describe"]
l = ["log"]
lb = ["log", "-r", "current()"]
lm = ["log", "-r", "::@"]
lo = ["log", "-r", "open()"]
r = ["rebase"]
s = ["status"]

[git]
push-branch-prefix = "ab/push-"

[revset-aliases]
'current()' = '(::@ ~ ::trunk())'
'open()' = '(mine() ~ ::trunk())::'
# Useful to rebase all branches with `jj r -s all:open_roots() -d main/master/develop/..`
'open_roots()' = 'roots(open())'

[template-aliases]
# Override the default short ID to use the absolute shortest, making it easier to use `-r <id>`
# in various `jj` commands
'format_short_id(id)' = 'id.shortest()'

[ui]
default-command = "status"

diff.tool = [
    "difft",
    "--display",
    "side-by-side-show-both",
    "--color=always",
    "$left",
    "$right",
]

diff-editor = "scm-diff-editor"
merge-editor = "scm-diff-editor"

[merge-tools.scm-diff-editor]
edit-args = ["--dir-diff", "$left", "$right"]
merge-args = [
    "--dir-diff",
    "--output", "$output",
    "--base", "$base",
    "$left", "$right",
]

[signing]
backend = "ssh"
key = "%SIGNING_SSH_KEY%"
sign-all = true
