prompt_order = [
    # "custom.failure",
    "username",
    "hostname",
    "custom.pwd",
    "git_branch",
    "git_commit",
    "git_state",
    # "git_status",
    # "custom.git_dirty",
    "python",
    "rust",
    "package",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "character",
]

# Active modules

[battery]
charging_symbol = ""
discharging_symbol = ""
full_symbol = ""

[character]
style_failure = "red"
style_success = "green"

[cmd_duration]
show_milliseconds = true
style = "yellow"

# [custom.failure]
# command = "echo -n $?"
# description = "Prints the last error code when it was different from 0."
# when = "true"
# style = "red"
# suffix = "] "
# prefix = "["

# [custom.git_dirty]
# command = "echo ✗"
# description = "Display a red cross when the current git repo is dirty."
# prefix = ""
# suffix = " "
# style = "red"
# when = "! ( test -d '.git' && git diff --quiet && git status -s >/dev/null )"

[custom.pwd]
command = "path_shortener"
description = "Prints the current working directory by compacting it."
style = "cyan"
suffix = " "
when = "true"

[git_branch]
style = "purple"
symbol = " "

[package]
style = "208"
symbol = " "

[python]
python_binary = "python3"
style = "yellow"
symbol = " "

[rust]
style = "red"
symbol = " "

# Disabled modules
[aws]
disabled = true
[conda]
disabled = true
[crystal]
disabled = true
[directory]
disabled = true
[docker_context]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[env_var]
disabled = true
[erlang]
disabled = true
# The following takes too long to run on big repo
[git_status]
disabled = true
[golang]
disabled = true
[java]
disabled = true
[julia]
disabled = true
[kubernetes]
disabled = true
[hg_branch]
disabled = true
[nim]
disabled = true
[nix_shell]
disabled = true
[nodejs]
disabled = true
[ocaml]
disabled = true
[php]
disabled = true
[purescript]
disabled = true
[ruby]
disabled = true
[singularity]
disabled = true
[terraform]
disabled = true
[time]
disabled = true
[zig]
disabled = true
