set nocompatible

if empty($DIRCONFIG)
  let $DIRCONFIG = ~/.config/
  silent !mkdir -p $DIRCONFIG
endif

let $vrtp = &rtp

set rtp=$DIRCONFIG/vim,$vrtp

source $DIRCONFIG/vim/rcs/base.vim
source $DIRCONFIG/vim/rcs/filetypes.vim

set rtp+=$DIRCONFIG/vim/after
