set nocompatible

if empty($DIRCONFIG)
  silent ! DIRCONFIG=$HOME/.config/ && export DIRCONFIG && mkdir -p $DIRCONFIG
endif

let $vrtp = &rtp

set rtp=$DIRCONFIG/vim,$vrtp

source $DIRCONFIG/vim/rcs/base.vim
source $DIRCONFIG/vim/rcs/filetypes.vim
source $DIRCONFIG/vim/rcs/plugins.vim

set rtp+=$DIRCONFIG/vim/after
