# Docs: <https://starship.rs/config/>

"$schema" = "https://starship.rs/config-schema.json"

command_timeout = 100
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$nix_shell\
$fill \
$cmd_duration\
$time\
$line_break\
$jobs\
$shell\
$status\
$character
"""

[character]
error_symbol = "[✖](bold red)"
success_symbol = "[❯](bold green)"

[cmd_duration]
show_milliseconds = true
format = "[\\($duration\\)]($style) "
style = "yellow italic"

[directory]
fish_style_pwd_dir_length = 1
repo_root_style = "cyan"
style = "cyan"
truncation_length = 1

[fill]
disabled = false
style = "grey"
symbol = "—"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "purple"

[git_state]
disabled = false

[git_status]
disabled = false
stashed = ""
style = "yellow"

[nix_shell]
disabled = false
format = "via [$symbol$state( \\($name\\))]($style) "
symbol = "❄️ "

[python]
python_binary = "python3"
style = "yellow"

[shell]
bash_indicator = "b"
disabled = false
fish_indicator = "🐠"
nu_indicator = "🐘"
zsh_indicator = "z"

[status]
disabled = false
format = "[$status]($style) "

[time]
disabled = false
format = "[$time]($style) "
style = "italic white"
