# Settings: <https://jj-vcs.github.io/jj/latest/config/>
"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

# <https://jj-vcs.github.io/jj/latest/config/#aliases>
[aliases]
b = ["bookmark"]
c = ["commit"]
cm = ["commit", "-m"]
d = ["diff"]
ds = ["describe"]
dt = ["diff", "--tool", "difft"]
g = ["git"]
gf = ["git", "fetch"]
gp = ["git", "push"]
gpa = ["git", "push", "--all"]
l = ["log"]
lb = ["log", "-r", "current()"]
lm = ["log", "-r", "::@"]
lo = ["log", "-r", "visible_open()"]
r = ["rebase"]
rs = ["rebase", "--source", "all:visible_open_roots()", "--destination"]
s = ["status"]
sq = ["squash"]

# <https://jj-vcs.github.io/jj/latest/config/#git-settings>
[git]
private-commits = "description(glob:'LOCAL:*')"
subprocess = true
# <https://jj-vcs.github.io/jj/latest/config/#automatically-signing-commits>
sign-on-push = true

[merge-tools.difft]
diff-args = [
  "--display",
  "side-by-side-show-both",
  "--color=always",
  "$left",
  "$right",
]

[revset-aliases]
"current()" = "(::@ ~ ::trunk())"
"open()" = "((::tracked_remote_bookmarks() | mine()) ~ ::trunk())::"
"visible_open()" = "(open() & ::visible_heads())::"
# Useful to rebase all branches with `jj r -s "all:visible_open_roots()" -d main/master/develop/..`
"visible_open_roots()" = "roots(visible_open())"

# <https://jj-vcs.github.io/jj/latest/config/#commit-signing>
# <https://jj-vcs.github.io/jj/latest/config/#ssh-signing>
[signing]
backend = "ssh"
behaviour = "own"
key = "~/.ssh/id_signing.pub"

[templates]
git_push_bookmark = '"ab/push-" ++ change_id.short()'

[template-aliases]
# Use a minimum length of 8, ensuring my Kitty config can detect such IDs all the time
"format_short_id(id)" = "id.shortest(8)"

# <https://jj-vcs.github.io/jj/latest/config/#ui-settings>
[ui]
# <https://jj-vcs.github.io/jj/latest/conflicts/#alternative-conflict-marker-styles>
conflict-marker-style = "snapshot"
default-command = "status"
# <https://jj-vcs.github.io/jj/latest/config/#diff-format>
diff-formatter = ":git"
pager = "delta"
