[snapshot]
max-new-file-size = "10MB"

[user]
name = "%DISPLAY_NAME%"
email = "%EMAIL%"

[aliases]
b = ["branch"]
c = ["commit"]
cm = ["commit", "-m"]
d = ["diff"]
dt = ["diff", "--tool", "difft"]
ds = ["describe"]
g = ["git"]
gf = ["git", "fetch"]
gp = ["git", "push"]
gpa = ["git", "push", "--all"]
l = ["log"]
lb = ["log", "-r", "current()"]
lm = ["log", "-r", "::@"]
lo = ["log", "-r", "open()"]
r = ["rebase"]
s = ["status"]
sq = ["squash"]

[git]
push-branch-prefix = "ab/push-"

[revset-aliases]
'current()' = '(::@ ~ ::trunk())'
'open()' = '(mine() ~ ::trunk())::'
# Useful to rebase all branches with `jj r -s all:open_roots() -d main/master/develop/..`
'open_roots()' = 'roots(open())'

[template-aliases]
# Override the default short ID to use the absolute shortest, making it easier to use `-r <id>`
# in various `jj` commands
'format_short_id(id)' = 'id.shortest()'

[ui]
default-command = "status"

pager = "delta"
diff.format = "git"

[merge-tools.difft]
diff-args = [
    "--display",
    "side-by-side-show-both",
    "--color=always",
    "$left",
    "$right",
]

[signing]
backend = "ssh"
key = "%SIGNING_SSH_KEY%"
sign-all = true
