# Copy mode via Chris Johnsen path 'reattach-to-user-namespace'
# Uncomment for macOS if needed
set -g default-command "reattach-to-user-namespace -l zsh"

# Copy mode
setw -g mode-keys vi
bind-key £ copy-mode
unbind-key [
unbind-key p ; bind-key p paste-buffer
bind-key -T copy-mode-vim Escape send-keys -X cancel
unbind-key -T copy-mode-vi Space     ;   bind-key -T copy-mode-vi v send-keys -X begin-selection
# Uncomment for macOS if needed
unbind-key -T copy-mode-vi Enter     ;   bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
unbind-key -T copy-mode-vi [         ;   bind-key -T copy-mode-vi [ send-keys -X begin-selection
unbind-key -T copy-mode-vi C-v       ;   bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
unbind-key -T copy-mode-vi ]         ;   bind-key -T copy-mode-vi ] send-keys -X copy-selection

# Colors
set -g default-terminal "screen-256color"

# Theme
source-file $XDG_CONFIG_HOME/tmux/themes/blue.tmuxtheme

# Turn the mouse on, but without copy mode dragging
set -g mouse on
unbind-key -n MouseDrag1Pane
unbind-key -Tcopy-mode MouseDrag1Pane

# Force reload of the config file
unbind-key r
bind-key r source-file $HOME/.tmux.conf
